version: 2.1

jobs:
  backend:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:nJ4fjs8DBnXE5nlOYmIhp+mdPAhHGegiK+RcxQ+2/kA"
      - checkout
      - run: cd backend && echo $SERVICE_ACCOUNT_KEY | base64 --decode > service-account-key.json && make verify
  sketch:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:nJ4fjs8DBnXE5nlOYmIhp+mdPAhHGegiK+RcxQ+2/kA"
      - checkout
      - run: git submodule update --init --recursive
      - run: cd sketch && make verify
  tag:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:nJ4fjs8DBnXE5nlOYmIhp+mdPAhHGegiK+RcxQ+2/kA"
      - checkout
      - run: sh scripts/tag.sh
  publish-backend:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:nJ4fjs8DBnXE5nlOYmIhp+mdPAhHGegiK+RcxQ+2/kA"
      - checkout
      - run: sh scripts/publish-backend.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - backend
      - sketch
      - tag:
          requires:
            - backend
            - sketch
          filters:
            branches:
              only: master
      - publish-backend:
          requires:
            - tag
          filters:
            branches:
              only: master
