version: 2.1

jobs:
  firmware:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: git submodule update --init --recursive
      - run: cd firmware && make verify
  tag:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: sh scripts/tag.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - firmware
      - tag:
          requires:
            - firmware
          filters:
            branches:
              only: master
