version: 2.1

jobs:
  backend:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: cd backend && echo $SERVICE_ACCOUNT_KEY | base64 --decode > service-account-key.json && make verify
  frontend:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: cd frontend && make verify
  esp32:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: git submodule update --init --recursive
      - run: cd esp32 && make verify
  tag:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: sh scripts/tag.sh
  publish-backend:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: sh scripts/publish-backend.sh
  publish-frontend:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - add_ssh_keys:
         fingerprints:
           - "SHA256:D5v5W7Cgjwp7YRMC+tmGu5h73CSzGBG/UbwgLMUs7/w"
      - checkout
      - run: sh scripts/publish-frontend.sh

workflows:
  version: 2
  test_and_publish:
    jobs:
      - backend
      - frontend
      - esp32
      - tag:
          requires:
            - backend
            - frontend
            - esp32
          filters:
            branches:
              only: master
      - publish-backend:
          requires:
            - tag
          filters:
            branches:
              only: master
      - publish-frontend:
          requires:
            - tag
          filters:
            branches:
              only: master
