version: "3.8"

services:
  smart-fluid-flow-meter-backend:
    build:
      dockerfile: dockerfiles/dev
      context: ../
    env_file: "../.env.sample"
    environment:
      FIRESTORE_EMULATOR_HOST: 'firestore:8200'
      GOOGLE_APPLICATION_CREDENTIALS: "/service-account-key.json"
    depends_on:
      mysql:
        condition: service_healthy
      firestore:
        condition: service_healthy
    volumes:
      - type: bind
        source: ../assets
        target: /smart-fluid-flow-meter/assets
      - type: bind
        source: ../src
        target: /smart-fluid-flow-meter/src
      - type: bind
        source: ../tests
        target: /smart-fluid-flow-meter/tests
      - type: bind
        source: ../Cargo.toml
        target: /smart-fluid-flow-meter/Cargo.toml
      - type: bind
        source: ../Cargo.lock
        target: /smart-fluid-flow-meter/Cargo.lock
      - type: bind
        source: ../build/target
        target: /smart-fluid-flow-meter/target
      - type: bind
        source: ../build/registry
        target: /usr/local/cargo/registry
      - type: bind
        source: ../service-account-key.json
        target: /service-account-key.json
    command: >
      sh -c "RUST_BACKTRACE=1 cargo test -- --nocapture"

  mysql:
    image: mysql:8.3.0
    environment:
      MYSQL_DATABASE: 'smart-fluid-flow-meter-backend'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    healthcheck:
        test: "mysqladmin ping -h localhost --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD"
        timeout: 20s
        retries: 10

  firestore:
    build:
      dockerfile: ../dockerfiles/firestore-emulator
      context: .
    ports:
      - '8200:8200'
    expose:
      - '8200'
    healthcheck:
        test: "curl 0.0.0.0:8200"
        timeout: 20s
        retries: 10
