version: "3.8"

services:
  smart-fluid-flow-meter-backend:
    env_file: "../.env.sample"
    build:
      dockerfile: dockerfiles/dev
      context: ../
    environment:
      FIRESTORE_EMULATOR_HOST: 'firestore:8200'
      GOOGLE_APPLICATION_CREDENTIALS: "/service-account-key.json"
    depends_on:
      firestore:
        condition: service_healthy
    volumes:
      - type: bind
        source: ../src
        target: /smart-fluid-flow-meter/src
      - type: bind
        source: ../tests
        target: /smart-fluid-flow-meter/tests
      - type: bind
        source: ../Cargo.toml
        target: /smart-fluid-flow-meter/Cargo.toml
      - type: bind
        source: ../Cargo.lock
        target: /smart-fluid-flow-meter/Cargo.lock
      - type: bind
        source: ../build/registry
        target: /usr/local/cargo/registry
      - type: bind
        source: ../build/target
        target: /smart-fluid-flow-meter/target
      - type: bind
        source: ../build/registry
        target: /usr/local/cargo/registry
      - type: bind
        source: ../service-account-key.json
        target: /service-account-key.json
    ports:
      - '3000:3000'
    expose:
      - '3000'
    command: >
      sh -c "RUST_BACKTRACE=1 cargo watch -x run"

  firestore:
    build:
      dockerfile: dockerfiles/firestore-emulator
      context: ../
    ports:
      - '8200:8200'
    expose:
      - '8200'
    healthcheck:
        test: "curl 0.0.0.0:8200"
        timeout: 20s
        retries: 10
